server:
  port: 10001
  servlet:
    context-path: /venus-server

spring:
  application:
    name: venus-server
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  datasource:
    url: jdbc:mysql://localhost/permission?characterEncoding=utf-8&useSSl=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/